name: Build curl with OpenSSL for Android

on:
  pull_request:
    branches:
      - main  # Adjust this branch to your requirements
  push:
    branches:
      - main  # Adjust this branch to your requirements

jobs:
  build:
    name: Build curl with OpenSSL for Android
    runs-on: ubuntu-latest  # Using latest Ubuntu version

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Android NDK
      uses: android-ndk/actions/setup@v1
      with:
        ndk-version: '27.0.12077973'  # Use the latest NDK version or your required version

    - name: Set up CMake
      uses: ccmake/cmake-action@v1
      with:
        cmake-version: '3.30.2'  # Update to the version you need

    - name: Install build dependencies
      run: sudo apt-get install -y \
        build-essential \
        pkg-config \
        zlib1g-dev \
        git

    - name: Download and build OpenSSL for Android
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git checkout OpenSSL_1_1_1-stable  # Use a stable version of OpenSSL
        ./Configure android-armv7 no-shared no-tests --prefix=${GITHUB_WORKSPACE}/openssl/android-armv7
        make
        make install

    - name: Build curl for Android with OpenSSL
      run: |
        export TOOLCHAIN=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=armeabi-v7a \
              -DANDROID_PLATFORM=android-21 \
              -DCMAKE_BUILD_TYPE=Release \
              -DHTTP_ONLY=ON \
              -DCURL_STATICLIB=ON \
              -DOPENSSL_ROOT_DIR=${GITHUB_WORKSPACE}/openssl/android-armv7 \
              ../curl
        make
        make install DESTDIR=${GITHUB_WORKSPACE}/output

    - name: Upload curl build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: curl-android
        path: output
        compression-level: 9
